{% set name = "jupyterlab_rise" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db03142fe386c8f07265970e0bbca752d2b851de994062b4e6f98af87893784a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.4.0
    - jupyterlab >=3.4.7,<4.0.0
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >=3.7
    - jupyterlab >=3.0.0,<4.0.0

test:
  imports:
    - jupyterlab_rise
  requires:
    - pip
  commands:
    - pip check
    - python -m jupyterlab.browser_check --no-chrome-test

about:
  home: https://github.com/jupyterlab-contrib/rise
  summary: 'RISE: "Live" Reveal.js JupyterLab Slideshow extension.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcollonval
